### ISSUE TITLE
Custom Legend Support?

### ISSUE THREAD

**Issue by shmuelios** [GraFiddle/angular-chart#110]
Hi There,

Great Project!

Was just having a mess around and wondered if it was possible to implement custom legend support.
http://c3js.org/samples/legend_custom.html

I've had a look around the code and don't think there is a way of currently getting to the object c3.generate() creates in the above example. do you think its worth exposing this from c3?

var chart = c3.generate({...})
chart.focus(id); chart.revert(); chart.toggle(id);
These functions seem pretty handy. could they be implemented?

Thanks
Sam

**Comment by shmuelios** [comment]
The reason I was requesting was for high amount of items in the legend.

I have now found if I align the legend right it does a good job anyway. :+1:

**Comment by maxklenk** [comment]
I generally try to keep the full state of the chart (which dimensions are shown/hidden) in the `options` object. So you could hide the default legend and add a custom one which updates the options. I will also have a look how to provide access to the chart itself since this was wished multiple times.

**Comment by shmuelios** [comment]
Yes that works also. slightly less interactive but does the job!
Thanks
