### ISSUE TITLE
How to call the C3js api function ?

### ISSUE THREAD

**Issue by youtalaoui** [GraFiddle/angular-chart#93]
hello, 

i want to know if it's possible de call the c3js api function to transform the chart to another type. and if yes how can it be done ? more specifically i want it to be binded to a scope variable. 
then i can dynamically create charts based on that type and some data and ng-repeat for example. 

Thank you

**Comment by maxklenk** [comment]
The way angular-chart works is by letting the user specify the chart options and it then calls internal the corresponding c3js API functions. So everything you have to do is to specify your data and the dimensions you want to show, as soon as you update your configuration the chart will update too.

To get started follow the [install guide](https://github.com/maxklenk/angular-chart#install). Two simple charts with `ng-repeat` can look like the following: 

```JavaScript
angular
  .module('myApp')
  .controller('Controller', function($scope) {
    var myData = [
        {
          sales: 130,
          income: 250
        }
      ];

    $scope.charts = [{
      data: myData,
      dimensions: {
        sales: {
          type: 'bar'
        },
        income: {
          axis: 'y2'
        }
      }
    }, {
      data: myData,
      dimensions: {
        sales: {
          type: 'line'
        },
        income: {}
      }
    }];

  });
```

```html
<div ng-controller="Controller">
  <div ng-repeat="options in charts">
    <angular-chart options="options"></angular-chart>
  </div>
</div>
```

Please try to integrate this in your system and tell me if it works for you.

**Comment by alexlangberg** [comment]
Let's say that after resizing the container of the chart, I now need to call [chart.resize()](http://c3js.org/samples/api_resize.html) without actually specifying any options - I just want it to resize to the current available width. How do I do this? Can I force a resize somehow else?

Perhaps it would be nice to expose the C3 chart itself for more advanced changes?

**Comment by gildasdubois** [comment]
Hi,

I'm also interrested by the exposition of the C3 chart itself!

Could you do this, please?

**Comment by redpandatronicsuk** [comment]
I found a way to expose the c3 chart object using angular chart. There are probably better ways of doing this, but for now this works:

1. In angular-chart.js around line 18: change:
    `scope: {
      options: '='
    },`
to:
    `scope: {
        options: '=',
        chart: '='
    },`
2. In the AngularChartService, after the generateChartFunction (around line 598), create a new getChart function:
    `ChartService.prototype.getChart = function() {
        return this.chart;
    };`
3. Around line 854, add this line to the body of the activate function:
    `$scope.chart = chartService.getChart();`

Now when creating a chart in your controller, create an empty object ({}), which we will use as a reference to the c3 chart, e.g:
`$scope.myC3chartApi = {};`

In the html when we create the chart, we add an extra field chart, e.g:
   ` <angular-chart options="..."
                   chart="myC3chartApi">
    </angular-chart>
    `
Now in the controller we have access to the c3 api and can do things like:

    $scope.$watch('chartContainerWidth', function(newWidth) {
        $scope.myC3chartApi.resize({width: newWidth});
    });
    
I don't think this is the best solution, but a workaround that seems to work.

**Comment by xtianjohns** [comment]
@maxklenk, is this closed because @redpandatronicsuk's solution is acceptable, or is this functionality not something you think is appropriate?

I think I understand the benefits of letting the directive handle most everything, but the c3 resize listener is for the window only, and if someone's parent div is resized due to a non-window-resize event, this seems like a good case for some extensibility in the directive API. Even if it's just a way to register listeners that will fire the resize event inside the directive, I think it would be helpful.

**Comment by maxklenk** [comment]
Hi @xtianjohns, I am not quite sure why I closed the issue without leaving a comment.

And you are right, it would be nice to have access to the c3js api, but I am not sure what's the best solution. Please give me feedback to to following solutions:

##### 1. @redpandatronicsuk Solution
 access throw directive attribute.
> Problem: When will the value be filled, it is null until the chart is rendered the first time

##### 2. Callback function
the directive allows to pass a callback function which will be called with the chart instance.

##### 3. Event
chart fires event on render
> Problem: when working with multiple charts, the matching with require additional work

**Comment by MyGuschtl** [comment]
I would also like to use chart api directly. I would prefer #1

**Comment by xtianjohns** [comment]
I thin I would prefer the first solution, but I share your concerns about being forced to handle timing. What are your thoughts about exposing a promise rather than the empty object?

The third solution interested me, I think that this could be solved by emitting an event on the directive's scope, with an event name encoded with the chart element's ID, if available? This would enforce the constraint that all elements have the same ID and can allow folks to easily handle registering listeners as long as they are close enough in the prototype chain.

The second option seems like it would be useful, but feels the least 'angular-y'. So... I guess, in loose order:

- First solution, with a promise
- Second solution
- First solution without a promise
- Third solution

**Comment by maxklenk** [comment]
Based on this issue and the pull request #100 of @wwwsevolod I implemented both the first solution with a promise and the third solution. So from now on you can access the c3js API once the chart is rendered using the [instance attribute](https://github.com/GraFiddle/angular-chart#instance):
```html
<angular-chart options="options" instance="instance"></angular-chart>
```

Or if you prefer to [listen to an event](https://github.com/GraFiddle/angular-chart#events) once the chart is rendered, you can do so too:
```javascript
$scope.$on('angular-chart-rendered', function(event, options, instance) {
  console.log(options, instance);
});
```

Please update to the [v0.5.0](https://github.com/GraFiddle/angular-chart/releases/tag/v0.5.0) release to use this new feature.

**Comment by xtianjohns** [comment]
Accommodates my use case 100%. Thanks, Max!
