### ISSUE TITLE
Stacked bar chart

### ISSUE THREAD

**Issue by flynhigher** [GraFiddle/angular-chart#98]
Hi,
How do you get the stacked bar chart that c3 can draw with "groups."
I tried by setting chart property like below.

`var group = ["chart1","chart2"];
options.chart = {data: {groups: group}};`

However, I get below error from c3.js line 1406.

`TypeError: config.data_groups[j].filter is not a function`

Has anyone successfully get this done?

Thanks,
Terry

**Comment by sebastianhenneberg** [comment]
Hi @flynhigher, the groups parameter of c3 is placed inside ``options.chart.data.groups``. Have a look at this [grafiddle](http://grafiddle.it/5685265389584384) to see how it works.

**Comment by mackler** [comment]
Apparently, even though the `groups` property is an array, it has no effect on the order in which the bars are stacked.  And even if you define an `order` function to fix that problem, _that_ has no effect on the order of the labels in the legend.

This is unfortunate, since having the dimensions in the stacked bars and the labels in the legend ordered differently makes a chart harder to read (and just plain looks wrong).

**Comment by maxklenk** [comment]
@mackler That's true, sadly. It is a problem of [c3](http://c3js.org/samples/data_order.html) the library we are building on top. Please request a solution for your problems in their issues.

**Comment by dugwood** [comment]
Hit the same issue, I was missing a level of arrays, as you did too:
`groups: ["chart1", "chart2"]` is wrong, it should be:
`groups: [ ["chart1", "chart2"] ]`

Else you can't make multiple groups.

One can argue that only one level would mean one group only, but it's more code and tests to run for the library.
